% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Dec-2024 22:06:18
%  MATLAB version: 24.2.0.2790852 (R2024b) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

len_of_list = saveVarsMat.len_of_list; % <1x1 py.int> unsupported class

my_str = 'Hello MATLAB';

mylist = saveVarsMat.mylist; % <1x1 py.list> unsupported class

py_math = saveVarsMat.py_math; % <1x1 py.module> unsupported class

result = 5;

reversed_str = saveVarsMat.reversed_str; % <1x1 py.str> unsupported class

clear saveVarsMat;
